server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  admin
    url: jdbc:postgresql://localhost:5432/travel_agency
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog-master_TA.xml
    drop-first: true

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true